//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttacheCase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttacheCase.Properties.Resources.ja-JP", typeof(Resources_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アタッシェケース4.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アタッシェケース4.
        /// </summary>
        public static string AttacheCase {
            get {
                return ResourceManager.GetString("AttacheCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再入力.
        /// </summary>
        public static string BreadcrumbsConfirmPassword {
            get {
                return ResourceManager.GetString("BreadcrumbsConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号.
        /// </summary>
        public static string BreadcrumbsExecuteDecrypt {
            get {
                return ResourceManager.GetString("BreadcrumbsExecuteDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化.
        /// </summary>
        public static string BreadcrumbsExecuteEncrypt {
            get {
                return ResourceManager.GetString("BreadcrumbsExecuteEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホーム.
        /// </summary>
        public static string BreadcrumbsHome {
            get {
                return ResourceManager.GetString("BreadcrumbsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード入力.
        /// </summary>
        public static string BreadcrumbsInputPassword {
            get {
                return ResourceManager.GetString("BreadcrumbsInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る(&amp;B).
        /// </summary>
        public static string ButtonTextBack {
            get {
                return ResourceManager.GetString("ButtonTextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル(&amp;C).
        /// </summary>
        public static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string ButtonTextOK {
            get {
                return ResourceManager.GetString("ButtonTextOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルへのアクセスが拒否されました。
        ///ファイルの読み書きができる場所（デスクトップ等）へ移動して再度実行してください。.
        /// </summary>
        public static string DialogMessageAccessDeny {
            get {
                return ResourceManager.GetString("DialogMessageAccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定を有効にするには、アタッシェケースの再起動が必要です。
        ///いまアプリケーションの再起動を行いますか？.
        /// </summary>
        public static string DialogMessageApplicationRestart {
            get {
                return ResourceManager.GetString("DialogMessageApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この暗号化ファイルは破壊されています。処理を中止します。.
        /// </summary>
        public static string DialogMessageAtcFileBroken {
            get {
                return ResourceManager.GetString("DialogMessageAtcFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダム値と、ゼロ値の設定の両方の設定を0にすることはできません。.
        /// </summary>
        public static string DialogMessageBothRandomAndZeroNotZero {
            get {
                return ResourceManager.GetString("DialogMessageBothRandomAndZeroNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード入力制限を超えたため、暗号化ファイルは破壊されました。.
        /// </summary>
        public static string DialogMessageBroken {
            get {
                return ResourceManager.GetString("DialogMessageBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この暗号化ファイルはすでに破壊されています。.
        /// </summary>
        public static string DialogMessageBrokenAlready {
            get {
                return ResourceManager.GetString("DialogMessageBrokenAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 破壊トークンを見つけられませんでした。暗号化ファイルではない可能性があります。.
        /// </summary>
        public static string DialogMessageBrokenDestroyNotFount {
            get {
                return ResourceManager.GetString("DialogMessageBrokenDestroyNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成する自己実行可能形式ファイルが、4GiB を超える可能性があります。実行ファイルとして動作しない可能性があります。続行しますか？
        ///(※実行ファイルとして起動しなくとも、暗号化ファイルとして復号することはできます。).
        /// </summary>
        public static string DialogMessageCreateSelfExecutableEileLargerThan4GiB {
            get {
                return ResourceManager.GetString("DialogMessageCreateSelfExecutableEileLargerThan4GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA公開鍵または秘密鍵の形式が違うか、XMLファイル形式ではありません。
        ///処理を中止します。.
        /// </summary>
        public static string DialogMessageCryptographicException {
            get {
                return ResourceManager.GetString("DialogMessageCryptographicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化するデータが見つかりません。ファイルは壊れています。
        ///復号できませんでした。.
        /// </summary>
        public static string DialogMessageDataNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードがちがうか、ファイルが破損している可能性があります。
        ///復号できませんでした。.
        /// </summary>
        public static string DialogMessageDecryptionError {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号時の指定されたパスワードファイルが見つかりません。処理を中止します。.
        /// </summary>
        public static string DialogMessageDecryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この商用ライセンスを削除しますか？.
        /// </summary>
        public static string DialogMessageDeleteCommercialLicense {
            get {
                return ResourceManager.GetString("DialogMessageDeleteCommercialLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号の元になった暗号化ファイルを削除しますか？.
        /// </summary>
        public static string DialogMessageDeleteEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDeleteEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化ファイルの元となったファイル及びフォルダーを削除しますか？.
        /// </summary>
        public static string DialogMessageDeleteOriginalFilesAndFolders {
            get {
                return ResourceManager.GetString("DialogMessageDeleteOriginalFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一時的に読み込まれた設定を破棄してレジストリから設定を読み込みます。よろしいですか？.
        /// </summary>
        public static string DialogMessageDicardTempSettingsAndLoadRegistry {
            get {
                return ResourceManager.GetString("DialogMessageDicardTempSettingsAndLoadRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルまたはディレクトリの一部が見つかりません。処理を中止します。.
        /// </summary>
        public static string DialogMessageDirectoryNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存先のフォルダーが見つかりません！　処理を中止します。.
        /// </summary>
        public static string DialogMessageDirectoryNotFount {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化するファイルまたはフォルダと、復号するものとが混在しているか、あるいは存在しないため、アタッシェケースはどちらの処理をすべきか判別できません。処理を中止します。.
        /// </summary>
        public static string DialogMessageDragAndDropMixedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDragAndDropMixedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用できないドライブまたは共有にアクセスしようとしました。
        ///処理を中止します。.
        /// </summary>
        public static string DialogMessageDriveNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDriveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化時の指定されたパスワードファイルが見つかりません。.
        /// </summary>
        public static string DialogMessageEncryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageEncryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号したファイルに実行ファイルが含まれています。以下のファイルを実行しますか？.
        /// </summary>
        public static string DialogMessageExecutableFile {
            get {
                return ResourceManager.GetString("DialogMessageExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの関連付けが正常に行われました。.
        /// </summary>
        public static string DialogMessageFileAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル関連付けツールが見つかりません。.
        /// </summary>
        public static string DialogMessageFileAssociationToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル関連付けツールが起動できませんでした。.
        /// </summary>
        public static string DialogMessageFileAssociationToolNotLaunched {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化ファイル内部で、不正なファイルインデックスがありました。.
        /// </summary>
        public static string DialogMessageFileIndexInvalid {
            get {
                return ResourceManager.GetString("DialogMessageFileIndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下の指定されたファイルリストの中のファイルが見つかりません！.
        /// </summary>
        public static string DialogMessageFileInFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileInFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下の指定されたファイルの文字エンコードが不明で読み取れません！.
        /// </summary>
        public static string DialogMessageFileListEncodingUnknown {
            get {
                return ResourceManager.GetString("DialogMessageFileListEncodingUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下の指定されたリストファイルが見つかりません！.
        /// </summary>
        public static string DialogMessageFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディスク上に存在しないファイルにアクセスしようとして失敗しました。
        ///処理を中止します。.
        /// </summary>
        public static string DialogMessageFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マネージドアセンブリが見つかりましたが、読み込むことができませんでした。
        ///処理を中止します。.
        /// </summary>
        public static string DialogMessageFileNotLoaded {
            get {
                return ResourceManager.GetString("DialogMessageFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除するファイル、またはフォルダーが見つかりません。.
        /// </summary>
        public static string DialogMessageFilesNotFoundDelete {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゴミ箱へ移動するファイル、またはフォルダーが見つかりません。.
        /// </summary>
        public static string DialogMessageFilesNotFoundMoveToTrash {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの関連付け解除が正常に行われました。.
        /// </summary>
        public static string DialogMessageFileUnAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileUnAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このファイルはアタッシェケースの上位バージョンで暗号化されています。
        ///復号できません。処理を中止します。.
        /// </summary>
        public static string DialogMessageHigherVersion {
            get {
                return ResourceManager.GetString("DialogMessageHigherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル、またはフォルダーパスが不正です。処理を中止します。.
        /// </summary>
        public static string DialogMessageInvalidFilePath {
            get {
                return ResourceManager.GetString("DialogMessageInvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化されたペアの秘密鍵ではありません。復号できませんでした。.
        /// </summary>
        public static string DialogMessageInvalidPrivateKey {
            get {
                return ResourceManager.GetString("DialogMessageInvalidPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下のドライブに空き容量がありません。処理を中止します。.
        /// </summary>
        public static string DialogMessageNoDiskSpace {
            get {
                return ResourceManager.GetString("DialogMessageNoDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化ファイルではありません。処理を中止します。.
        /// </summary>
        public static string DialogMessageNotAtcFile {
            get {
                return ResourceManager.GetString("DialogMessageNotAtcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードファイルにフォルダーを使うことはできません。.
        /// </summary>
        public static string DialogMessageNotDirectoryInPasswordFile {
            get {
                return ResourceManager.GetString("DialogMessageNotDirectoryInPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルのハッシュ値が異なります。ファイルが壊れたか、改ざんされた可能性があります。処理を中止します。.
        /// </summary>
        public static string DialogMessageNotSameHash {
            get {
                return ResourceManager.GetString("DialogMessageNotSameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowsのファイル名には以下の文字が使えません！
        ///
        ///\\ / : , * ? \&quot; &lt; &gt; |.
        /// </summary>
        public static string DialogMessageNotUseWindowsFileName {
            get {
                return ResourceManager.GetString("DialogMessageNotUseWindowsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現状、パスワード付きZIPファイルの復号には対応していません。.
        /// </summary>
        public static string DialogMessageNotZipDecrypted {
            get {
                return ResourceManager.GetString("DialogMessageNotZipDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows XP互換モードの設定が完了されませんでした。この設定が行われないと、アプリケーションを起動することができません。
        ///もう一度、初めから設定をやり直してください。.
        /// </summary>
        public static string DialogMessageNoXpCompatiblityMode {
            get {
                return ResourceManager.GetString("DialogMessageNoXpCompatiblityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号したファイルが{0}個以上あります。
        ///それでもすべてのファイルを関連付けられたアプリケーションで開きますか？.
        /// </summary>
        public static string DialogMessageOpenMultipleFiles {
            get {
                return ResourceManager.GetString("DialogMessageOpenMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オペレーティングシステムが I/O エラーまたは特定の種類のセキュリティエラーのために
        ///アクセスを拒否しました。処理を中止します。.
        /// </summary>
        public static string DialogMessageOsDeniesAccess {
            get {
                return ResourceManager.GetString("DialogMessageOsDeniesAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動作設定で指定されたパスワードファイルが見つかりません。.
        /// </summary>
        public static string DialogMessagePasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessagePasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ２つのパスワードが一致しません。入力し直してください。.
        /// </summary>
        public static string DialogMessagePasswordsNotMatch {
            get {
                return ResourceManager.GetString("DialogMessagePasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パス名または完全修飾ファイル名がシステム定義の最大長を超えています。
        ///処理を中止します。.
        /// </summary>
        public static string DialogMessagePathTooLong {
            get {
                return ResourceManager.GetString("DialogMessagePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下の指定された場所にレジストレーションコードのテキストファイルが見つかりません！.
        /// </summary>
        public static string DialogMessageRegistrationCodeFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストレーションコードを削除できませんでした。.
        /// </summary>
        public static string DialogMessageRegistrationCodeNotDeleted {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常にレジストレーションコードの登録が行われませんでした。.
        /// </summary>
        public static string DialogMessageRegistrationCodeNotRegistered {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSAで暗号化された公開鍵と異なるペアの鍵が指定されています。復号できません。
        ///処理を中止します。.
        /// </summary>
        public static string DialogMessageRsaKeyGuidNotMatch {
            get {
                return ResourceManager.GetString("DialogMessageRsaKeyGuidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セットアップツールが見つかりません！.
        /// </summary>
        public static string DialogMessageSetupToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageSetupToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドラインオプションからの一時設定を利用しているため、メインの設定を反映させることができません。.
        /// </summary>
        public static string DialogMessageTempSettingsFromCommandLine {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsFromCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIファイルからの一時設定を利用しているため、メインの設定を反映させることができません。.
        /// </summary>
        public static string DialogMessageTempSettingsFromIniFile {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsFromIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一時的に読み込まれた設定を現在の設定としてレジストリに反映させます。よろしいですか？.
        /// </summary>
        public static string DialogMessageTempSettingsToCurrent {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsToCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 想定外のファイルです。復号することができません。.
        /// </summary>
        public static string DialogMessageUnexpectedDecryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedDecryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予期せぬエラーが発生しました。処理を中止します。.
        /// </summary>
        public static string DialogMessageUnexpectedError {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        public static string DialogTitleAlert {
            get {
                return ResourceManager.GetString("DialogTitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一つにまとめる暗号化ファイル名の入力.
        /// </summary>
        public static string DialogTitleAllPackFiles {
            get {
                return ResourceManager.GetString("DialogTitleAllPackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドライン.
        /// </summary>
        public static string DialogTitleCommandLine {
            get {
                return ResourceManager.GetString("DialogTitleCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化するファイルの選択.
        /// </summary>
        public static string DialogTitleEncryptSelectFiles {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化するフォルダーの選択.
        /// </summary>
        public static string DialogTitleEncryptSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        public static string DialogTitleInfomation {
            get {
                return ResourceManager.GetString("DialogTitleInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 問い合わせ.
        /// </summary>
        public static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリ.
        /// </summary>
        public static string DialogTitleRegistry {
            get {
                return ResourceManager.GetString("DialogTitleRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開鍵と秘密鍵の保存.
        /// </summary>
        public static string DialogTitleSavePublicAndPrivateKey {
            get {
                return ResourceManager.GetString("DialogTitleSavePublicAndPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化ファイルを選択.
        /// </summary>
        public static string DialogTitleSelectEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogTitleSelectEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードファイルを選択.
        /// </summary>
        public static string DialogTitleSelectPasswordFile {
            get {
                return ResourceManager.GetString("DialogTitleSelectPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動作設定.
        /// </summary>
        public static string DialogTitleSettings {
            get {
                return ResourceManager.GetString("DialogTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常に復号するファイル、またはフォルダーを保存する先のフォルダーを選択してください。.
        /// </summary>
        public static string folderBrowserDialogSaveToDecryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToDecryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常に暗号化ファイルを保存する先のフォルダーを選択してください。.
        /// </summary>
        public static string folderBrowserDialogSaveToEncryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToEncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常にZIPファイルを保存する先のフォルダーを選択してください。.
        /// </summary>
        public static string folderBrowserDialogSaveToZipFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定ファイル（INIファイル）読み込み中は変更できません.
        /// </summary>
        public static string groupBoxCanNotChange {
            get {
                return ResourceManager.GetString("groupBoxCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定ファイル（INIファイル）オプション：.
        /// </summary>
        public static string groupBoxReadIniFile {
            get {
                return ResourceManager.GetString("groupBoxReadIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中止.
        /// </summary>
        public static string labelCaptionAborted {
            get {
                return ResourceManager.GetString("labelCaptionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキップ.
        /// </summary>
        public static string labelCaptionAllSkipped {
            get {
                return ResourceManager.GetString("labelCaptionAllSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string labelCaptionCanceled {
            get {
                return ResourceManager.GetString("labelCaptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了.
        /// </summary>
        public static string labelCaptionCompleted {
            get {
                return ResourceManager.GetString("labelCaptionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        public static string labelCaptionError {
            get {
                return ResourceManager.GetString("labelCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードが一致しません。無効のパスワードです。.
        /// </summary>
        public static string labelCaptionPasswordInvalid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードが一致しました。有効です。.
        /// </summary>
        public static string labelCaptionPasswordValid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コードが正しくありません。.
        /// </summary>
        public static string labelCodeIncorrect {
            get {
                return ResourceManager.GetString("labelCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商用ライセンス適用.
        /// </summary>
        public static string labelCommercialLicenseApplicable {
            get {
                return ResourceManager.GetString("labelCommercialLicenseApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル、またはフォルダーの完全削除中にエラーが発生しました。.
        /// </summary>
        public static string labelCompleteDeleteError {
            get {
                return ResourceManager.GetString("labelCompleteDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル、またはフォルダーの完全削除がキャンセルされました。.
        /// </summary>
        public static string labelCompleteDeleteFileCanceled {
            get {
                return ResourceManager.GetString("labelCompleteDeleteFileCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル、またはフォルダーの完全削除は正常に完了しました。.
        /// </summary>
        public static string labelCompleteDeletingCompleted {
            get {
                return ResourceManager.GetString("labelCompleteDeletingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定のファイル及びフォルダーは、完全削除されました。.
        /// </summary>
        public static string labelCompletelyDeleteCompleted {
            get {
                return ResourceManager.GetString("labelCompletelyDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルに対して圧縮を行いません。.
        /// </summary>
        public static string labelCompressMsgNone {
            get {
                return ResourceManager.GetString("labelCompressMsgNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圧縮操作が完了するまで時間がかかる場合でも、最適な圧縮を行います。.
        /// </summary>
        public static string labelCompressMsgOptimal {
            get {
                return ResourceManager.GetString("labelCompressMsgOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速.
        /// </summary>
        public static string labelCompressTitleFastest {
            get {
                return ResourceManager.GetString("labelCompressTitleFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無圧縮.
        /// </summary>
        public static string labelCompressTitleNone {
            get {
                return ResourceManager.GetString("labelCompressTitleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最適.
        /// </summary>
        public static string labelCompressTitleOptimal {
            get {
                return ResourceManager.GetString("labelCompressTitleOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下のフォルダーはすでに存在しています。上書きして保存しますか？.
        /// </summary>
        public static string labelConfirmToOverwriteDir {
            get {
                return ResourceManager.GetString("labelConfirmToOverwriteDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下のファイルはすでに存在しています。上書きして保存しますか？.
        /// </summary>
        public static string labelConfirmToOverwriteFile {
            get {
                return ResourceManager.GetString("labelConfirmToOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号処理はキャンセルされました。.
        /// </summary>
        public static string labelDecryptionCanceled {
            get {
                return ResourceManager.GetString("labelDecryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号処理はキャンセルされました。.
        /// </summary>
        public static string labelDecyptionCanceled {
            get {
                return ResourceManager.GetString("labelDecyptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルまたはフォルダーの削除中にエラーが発生しました。.
        /// </summary>
        public static string labelDeleteError {
            get {
                return ResourceManager.GetString("labelDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バイト.
        /// </summary>
        public static string labelDeleteMessageBytes {
            get {
                return ResourceManager.GetString("labelDeleteMessageBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乱数.
        /// </summary>
        public static string labelDeleteTypeRandom {
            get {
                return ResourceManager.GetString("labelDeleteTypeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゼロ.
        /// </summary>
        public static string labelDeleteTypeZeros {
            get {
                return ResourceManager.GetString("labelDeleteTypeZeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZipAes128 値と WinZipAes256 値は zip 仕様に含まれていませんが、WinZip のベンダー固有の拡張を使用することを意味しています。相互運用可能な Zip アーカイブを生成するには、これらの値を使用しないでください。たとえば、WinZipAes256 を使用して zip アーカイブを生成する場合、Windows XP および Vista で Windows Explorer で開くことができますが、エントリーを解凍することはできません。解凍しようとすると、「未定義のエラー」となります。このため、WinZip の AES 暗号化を使用した zip アーカイブは、実際にはまったく zip アーカイブでないと言う人もいます。この方法で生成された zip アーカイブは、WinZip ツール (バージョン 11 以降) で読み込むことができます。.
        /// </summary>
        public static string labelEncryptAlgoDescriptionAES {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkzipWeak は Zip 2.0 暗号化を使用することを意味します。これは弱い暗号化であり、解読可能であることが知られています。
        ///
        ///相互運用性に関する注意: 値 PkzipWeak と None は PKWARE の zip 仕様 で規定されており、「標準」と見なされます。これらのオプションを使用して生成された zip アーカイブは、Windows エクスプローラーを含む他の多くの zip ツールと相互運用性があります。.
        /// </summary>
        public static string labelEncryptAlgoDescriptionPkzipWeak {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionPkzipWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己実行形式ファイルが 4GiB を超える可能性があるため、暗号化処理を中止しました。.
        /// </summary>
        public static string labelEncryptionAbortedToExceed4GiB {
            get {
                return ResourceManager.GetString("labelEncryptionAbortedToExceed4GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化の処理はキャンセルされました。.
        /// </summary>
        public static string labelEncryptionCanceled {
            get {
                return ResourceManager.GetString("labelEncryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号するための準備をしています....
        /// </summary>
        public static string labelGettingReadyForDecryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化するための準備をしています....
        /// </summary>
        public static string labelGettingReadyForEncryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認のためもう一度パスワードを入力してください：.
        /// </summary>
        public static string labelInputPasswordAgainToConfirm {
            get {
                return ResourceManager.GetString("labelInputPasswordAgainToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスに不正な文字列があります。置換して復号しますか？.
        /// </summary>
        public static string labelInvalidChar {
            get {
                return ResourceManager.GetString("labelInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開鍵または秘密鍵は読み込まれませんでした。.
        /// </summary>
        public static string labelKeyFileNotLoaded {
            get {
                return ResourceManager.GetString("labelKeyFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全削除.
        /// </summary>
        public static string labellabelCompletelyDelete {
            get {
                return ResourceManager.GetString("labellabelCompletelyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゴミ箱へ.
        /// </summary>
        public static string labelMoveToTrash {
            get {
                return ResourceManager.GetString("labelMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル、またはフォルダーのゴミ箱への移動がキャンセルされました。.
        /// </summary>
        public static string labelMoveToTrashCanceled {
            get {
                return ResourceManager.GetString("labelMoveToTrashCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル、またはフォルダーのゴミ箱への移動が完了しました。.
        /// </summary>
        public static string labelMoveToTrashCompleted {
            get {
                return ResourceManager.GetString("labelMoveToTrashCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常削除.
        /// </summary>
        public static string labelNormalDelete {
            get {
                return ResourceManager.GetString("labelNormalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルまたはフォルダーの削除をキャンセルしました。.
        /// </summary>
        public static string labelNormalDeleteCanceled {
            get {
                return ResourceManager.GetString("labelNormalDeleteCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定のファイル及びフォルダーは削除されました。.
        /// </summary>
        public static string labelNormalDeleteCompleted {
            get {
                return ResourceManager.GetString("labelNormalDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード：.
        /// </summary>
        public static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードファイル：.
        /// </summary>
        public static string labelPasswordFile {
            get {
                return ResourceManager.GetString("labelPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すでにパスワードファイルが入力済みです：.
        /// </summary>
        public static string labelPasswordFileIsEnteredAlready {
            get {
                return ResourceManager.GetString("labelPasswordFileIsEnteredAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記憶パスワードを破棄して新しいパスワードを入力する：.
        /// </summary>
        public static string labelPasswordInputNewPassword {
            get {
                return ResourceManager.GetString("labelPasswordInputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記憶パスワード：.
        /// </summary>
        public static string labelPasswordMemorized {
            get {
                return ResourceManager.GetString("labelPasswordMemorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドラインオプションからのパスワード：.
        /// </summary>
        public static string labelPasswordOfCommandLineOption {
            get {
                return ResourceManager.GetString("labelPasswordOfCommandLineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全削除は正常に完了しました。.
        /// </summary>
        public static string labelProcessDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化のための準備をしています....
        /// </summary>
        public static string labelProcessGettingRedyForEncryption {
            get {
                return ResourceManager.GetString("labelProcessGettingRedyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復号しています....
        /// </summary>
        public static string labelProcessNameDecrypt {
            get {
                return ResourceManager.GetString("labelProcessNameDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除しています....
        /// </summary>
        public static string labelProcessNameDelete {
            get {
                return ResourceManager.GetString("labelProcessNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全削除をしています....
        /// </summary>
        public static string labelProcessNameDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessNameDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化しています....
        /// </summary>
        public static string labelProcessNameEncrypt {
            get {
                return ResourceManager.GetString("labelProcessNameEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゴミ箱へ移動しています....
        /// </summary>
        public static string labelProcessNameMoveToTrash {
            get {
                return ResourceManager.GetString("labelProcessNameMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開鍵暗号.
        /// </summary>
        public static string labelRsa {
            get {
                return ResourceManager.GetString("labelRsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ここに、暗号化または復号したいファイル・フォルダーをドラッグ＆ドロップしてください。先に公開鍵、秘密鍵をドラッグ＆ドロップすることもできます。.
        /// </summary>
        public static string labelRsaDescription {
            get {
                return ResourceManager.GetString("labelRsaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化ファイルが読み込まれました。復号するための秘密鍵をここへドラッグ＆ドロップしてください。.
        /// </summary>
        public static string labelRsaEncryptedFileloaded {
            get {
                return ResourceManager.GetString("labelRsaEncryptedFileloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルまたはフォルダーが読み込まれました。暗号化するための公開鍵をここへドラッグ＆ドロップしてください。.
        /// </summary>
        public static string labelRsaFilesloaded {
            get {
                return ResourceManager.GetString("labelRsaFilesloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ここに、暗号化または復号したいファイル・フォルダーをドラッグ＆ドロップしてください。先に公開鍵、秘密鍵をドラッグ＆ドロップすることもできます。.
        /// </summary>
        public static string labelRsaMessage {
            get {
                return ResourceManager.GetString("labelRsaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秘密鍵.
        /// </summary>
        public static string labelRsaPrivateKey {
            get {
                return ResourceManager.GetString("labelRsaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秘密鍵が読み込まれました。復号する暗号化ファイルをここへドラッグ＆ドロップしてください。.
        /// </summary>
        public static string labelRsaPrivateKeyloaded {
            get {
                return ResourceManager.GetString("labelRsaPrivateKeyloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開鍵.
        /// </summary>
        public static string labelRsaPublicKey {
            get {
                return ResourceManager.GetString("labelRsaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開鍵が読み込まれました。暗号化したいファイルまたはフォルダーをここへドラッグ＆ドロップしてください。.
        /// </summary>
        public static string labelRsaPublicKeyloaded {
            get {
                return ResourceManager.GetString("labelRsaPublicKeyloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効なコードです。.
        /// </summary>
        public static string labelValidCode {
            get {
                return ResourceManager.GetString("labelValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圧縮後のファイルが最適な圧縮でなくても、圧縮操作はできるだけ迅速に完了します。.
        /// </summary>
        public static string lbelCompressMsgFastest {
            get {
                return ResourceManager.GetString("lbelCompressMsgFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新情報の取得に失敗しました。.
        /// </summary>
        public static string linkLabelCheckForUpdatesFailed {
            get {
                return ResourceManager.GetString("linkLabelCheckForUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新があるかチェックしています....
        /// </summary>
        public static string linkLabelCheckingForUpdates {
            get {
                return ResourceManager.GetString("linkLabelCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すでに最新バージョンです。.
        /// </summary>
        public static string linkLabelLatestVersion {
            get {
                return ResourceManager.GetString("linkLabelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新バージョンの更新があります！.
        /// </summary>
        public static string linkLabelLatestVersionReleased {
            get {
                return ResourceManager.GetString("linkLabelLatestVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中止する(&amp;A).
        /// </summary>
        public static string MessageBoxButtonAbort {
            get {
                return ResourceManager.GetString("MessageBoxButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル(&amp;C).
        /// </summary>
        public static string MessageBoxButtonCancel {
            get {
                return ResourceManager.GetString("MessageBoxButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 続行する(&amp;P).
        /// </summary>
        public static string MessageBoxButtonProceed {
            get {
                return ResourceManager.GetString("MessageBoxButtonProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細情報：
        ///ファイルが正しく復号されるか、暗号化前にその元ファイルの一意の値（MD5ハッシュ）を書き込んでおき、復号時にそれを確認します。
        ///
        ///- 暗号化ファイルのハッシュ値: {0}
        ///- 復号後のファイルハッシュ値: {1}
        ///
        ///もし、これらのハッシュ値が一致しない場合、ファイルは元の状態から変更されているか、破損している可能性があります。この情報をもとに、復号を続行するかどうかをご判断ください。.
        /// </summary>
        public static string MessageBoxDetailedInformation {
            get {
                return ResourceManager.GetString("MessageBoxDetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下のファイルの確認に失敗しました。ファイルが変更されたか、破損している可能性があります。どのように進めますか？.
        /// </summary>
        public static string MessageBoxFileVerifyFailed {
            get {
                return ResourceManager.GetString("MessageBoxFileVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細を隠す(&amp;D).
        /// </summary>
        public static string MessageBoxHideDetails {
            get {
                return ResourceManager.GetString("MessageBoxHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細を表示(&amp;D).
        /// </summary>
        public static string MessageBoxShowDetails {
            get {
                return ResourceManager.GetString("MessageBoxShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべてのファイル(*.*)|*.*.
        /// </summary>
        public static string OpenDialogFilterAllFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイコンファイル(*.ico)|*.ico|すべてのファイル(*.*)|*.*.
        /// </summary>
        public static string OpenDialogFilterIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイコンファイルの選択.
        /// </summary>
        public static string OpenDialogTitleIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogTitleIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化ファイル (*.atc)|*.atc|すべてのファイル (*.*)|*.*.
        /// </summary>
        public static string SaveDialogFilterAtcFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterAtcFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIファイル (*.ini)|*.ini|すべてのファイル (*.*)|*.*.
        /// </summary>
        public static string SaveDialogFilterIniFilles {
            get {
                return ResourceManager.GetString("SaveDialogFilterIniFilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己実行形式(*.exe)|*.exe|すべてのファイル(*.*)|*.*いｓ.
        /// </summary>
        public static string SaveDialogFilterSelfExeFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterSelfExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脆弱　.
        /// </summary>
        public static string zxcvbnLabel00 {
            get {
                return ResourceManager.GetString("zxcvbnLabel00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弱い　.
        /// </summary>
        public static string zxcvbnLabel01 {
            get {
                return ResourceManager.GetString("zxcvbnLabel01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やや弱い.
        /// </summary>
        public static string zxcvbnLabel02 {
            get {
                return ResourceManager.GetString("zxcvbnLabel02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全　.
        /// </summary>
        public static string zxcvbnLabel03 {
            get {
                return ResourceManager.GetString("zxcvbnLabel03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高安全.
        /// </summary>
        public static string zxcvbnLabel04 {
            get {
                return ResourceManager.GetString("zxcvbnLabel04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空文字.
        /// </summary>
        public static string zxcvbnLabelEmpty {
            get {
                return ResourceManager.GetString("zxcvbnLabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to もう１，２単語追加してください。珍しい言葉が優れています。.
        /// </summary>
        public static string zxcvbnSuggestionAddAnotherWordOrTwo {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAddAnotherWordOrTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて大文字は、すべて小文字と同じくらい簡単に推測できます。.
        /// </summary>
        public static string zxcvbnSuggestionAllCapsEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAllCapsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたに関係うる年号や日付は避けてください。.
        /// </summary>
        public static string zxcvbnSuggestionAvoidDatesYearsAssociatedYou {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidDatesYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単語や文字の繰り返しを避けてください。.
        /// </summary>
        public static string zxcvbnSuggestionAvoidRepeatedWordsAndChars {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidRepeatedWordsAndChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 順番や並びのあるものは避けてください。.
        /// </summary>
        public static string zxcvbnSuggestionAvoidSequences {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい年号は避けてください。
        ///特にあなたに関係する年号は避けるべきです。.
        /// </summary>
        public static string zxcvbnSuggestionAvoidYearsAssociatedYou {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大文字はあまり役に立ちません。.
        /// </summary>
        public static string zxcvbnSuggestionCapsDontHelp {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionCapsDontHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空文字です。
        ///少数の単語を使用して、一般的なフレーズを避けてください。
        ///記号、数字、または大文字は不要です。.
        /// </summary>
        public static string zxcvbnSuggestionDefault {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空文字です。.
        /// </summary>
        public static string zxcvbnSuggestionEmpty {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「a」の代わりに 「@」のような予測可能な代用はあまり役に立ちません。.
        /// </summary>
        public static string zxcvbnSuggestionPredictableSubstitutionsEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionPredictableSubstitutionsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逆の言葉を推測するのはそれほど難しくありません。.
        /// </summary>
        public static string zxcvbnSuggestionReversedWordEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionReversedWordEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to より長いターンでより長いキーボードパターンを使ってください。.
        /// </summary>
        public static string zxcvbnSuggestionUseLongerKeyboardPattern {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionUseLongerKeyboardPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒント.
        /// </summary>
        public static string zxcvbnToolTipTitleSuggestions {
            get {
                return ResourceManager.GetString("zxcvbnToolTipTitleSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        public static string zxcvbnToolTipTitleWarning {
            get {
                return ResourceManager.GetString("zxcvbnToolTipTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付はしばしば推測しやすいことがあります。.
        /// </summary>
        public static string zxcvbnWarnigDatesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarnigDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般名と姓は簡単に推測できます。.
        /// </summary>
        public static string zxcvbnWarningCommonNameSurnamesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningCommonNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to これは非常に一般的なパスワードです。.
        /// </summary>
        public static string zxcvbnWarningCommonPasswords {
            get {
                return ResourceManager.GetString("zxcvbnWarningCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付はしばしば推測しやすいことがあります。.
        /// </summary>
        public static string zxcvbnWarningDatesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空文字です。.
        /// </summary>
        public static string zxcvbnWarningDefault {
            get {
                return ResourceManager.GetString("zxcvbnWarningDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空文字です。.
        /// </summary>
        public static string zxcvbnWarningEmpty {
            get {
                return ResourceManager.GetString("zxcvbnWarningEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前と姓自体は簡単に推測できます。.
        /// </summary>
        public static string zxcvbnWarningNameSurnamesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい年号は推測しやすいです。.
        /// </summary>
        public static string zxcvbnWarningRecentYearsEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningRecentYearsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「aaa」のような繰り返しは簡単に推測できます。.
        /// </summary>
        public static string zxcvbnWarningRepeatsLikeAaaEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningRepeatsLikeAaaEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「abcabcabc」のような繰り返しは、「abc」よりも推測がやや困難です。.
        /// </summary>
        public static string zxcvbnWarningRepeatsLikeAbcSlighterHarder {
            get {
                return ResourceManager.GetString("zxcvbnWarningRepeatsLikeAbcSlighterHarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcや6543のようなシーケンスは簡単に推測できます。.
        /// </summary>
        public static string zxcvbnWarningSequenceAbcEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningSequenceAbcEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 短いキーボードパターンは簡単に推測できます。.
        /// </summary>
        public static string zxcvbnWarningShortKeyboardPatterns {
            get {
                return ResourceManager.GetString("zxcvbnWarningShortKeyboardPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to これは一般的に使用されるパスワードに似ています。.
        /// </summary>
        public static string zxcvbnWarningSimilarCommonPasswords {
            get {
                return ResourceManager.GetString("zxcvbnWarningSimilarCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真っ直ぐな列のキーは推測しやすくなります。.
        /// </summary>
        public static string zxcvbnWarningStraightRow {
            get {
                return ResourceManager.GetString("zxcvbnWarningStraightRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to これはトップ10の一般的なパスワードです。.
        /// </summary>
        public static string zxcvbnWarningTop10Passwords {
            get {
                return ResourceManager.GetString("zxcvbnWarningTop10Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単語だけで推測するのが簡単です。.
        /// </summary>
        public static string zxcvbnWarningWordEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningWordEasy", resourceCulture);
            }
        }
    }
}
