//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttacheCase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttacheCase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachéCase4.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachéCase4.
        /// </summary>
        public static string AttacheCase {
            get {
                return ResourceManager.GetString("AttacheCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string BreadcrumbsConfirmPassword {
            get {
                return ResourceManager.GetString("BreadcrumbsConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string BreadcrumbsExecuteDecrypt {
            get {
                return ResourceManager.GetString("BreadcrumbsExecuteDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string BreadcrumbsExecuteEncrypt {
            get {
                return ResourceManager.GetString("BreadcrumbsExecuteEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BreadcrumbsHome {
            get {
                return ResourceManager.GetString("BreadcrumbsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Password.
        /// </summary>
        public static string BreadcrumbsInputPassword {
            get {
                return ResourceManager.GetString("BreadcrumbsInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Back.
        /// </summary>
        public static string ButtonTextBack {
            get {
                return ResourceManager.GetString("ButtonTextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string ButtonTextOK {
            get {
                return ResourceManager.GetString("ButtonTextOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the file has been denied.
        ///Move to a place (eg Desktop) where you can read and write files and try again..
        /// </summary>
        public static string DialogMessageAccessDeny {
            get {
                return ResourceManager.GetString("DialogMessageAccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable this setting, you will need to restart the AttacheCase.
        ///Do you restart AttacheCase now?.
        /// </summary>
        public static string DialogMessageApplicationRestart {
            get {
                return ResourceManager.GetString("DialogMessageApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This encrypted file is broken. The process is aborted..
        /// </summary>
        public static string DialogMessageAtcFileBroken {
            get {
                return ResourceManager.GetString("DialogMessageAtcFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Random setting and Zero setting are not able to set to zero..
        /// </summary>
        public static string DialogMessageBothRandomAndZeroNotZero {
            get {
                return ResourceManager.GetString("DialogMessageBothRandomAndZeroNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted file has been broken because it exceeded the limit number of inputting password..
        /// </summary>
        public static string DialogMessageBroken {
            get {
                return ResourceManager.GetString("DialogMessageBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted file has already been destroyed..
        /// </summary>
        public static string DialogMessageBrokenAlready {
            get {
                return ResourceManager.GetString("DialogMessageBrokenAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The broken token could not found. The file may not be an encrypted file..
        /// </summary>
        public static string DialogMessageBrokenDestroyNotFount {
            get {
                return ResourceManager.GetString("DialogMessageBrokenDestroyNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The self-executable file you create may exceed 4 GiB.The file may not work as an executable.Would you like to continue?
        ///(*It can be decrypted as an encrypted file even if it is not launched as an executable file.).
        /// </summary>
        public static string DialogMessageCreateSelfExecutableEileLargerThan4GiB {
            get {
                return ResourceManager.GetString("DialogMessageCreateSelfExecutableEileLargerThan4GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RSA public or private key is in a different format or is not in XML file format.
        ///The process is aborted..
        /// </summary>
        public static string DialogMessageCryptographicException {
            get {
                return ResourceManager.GetString("DialogMessageCryptographicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted data not found. The file is broken.
        ///Decryption failed..
        /// </summary>
        public static string DialogMessageDataNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid, or the encrypted file might have been broken. Decryption is aborted..
        /// </summary>
        public static string DialogMessageDecryptionError {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password file is not found in decryption. The process is aborted..
        /// </summary>
        public static string DialogMessageDecryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this commercial license?.
        /// </summary>
        public static string DialogMessageDeleteCommercialLicense {
            get {
                return ResourceManager.GetString("DialogMessageDeleteCommercialLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the encypted file(s) that are the source of the decryption?.
        /// </summary>
        public static string DialogMessageDeleteEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDeleteEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the files and folders that are the source of the encrypted file?.
        /// </summary>
        public static string DialogMessageDeleteOriginalFilesAndFolders {
            get {
                return ResourceManager.GetString("DialogMessageDeleteOriginalFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard the loaded temporary settings and load the settings from the registry. Are you sure?.
        /// </summary>
        public static string DialogMessageDicardTempSettingsAndLoadRegistry {
            get {
                return ResourceManager.GetString("DialogMessageDicardTempSettingsAndLoadRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part of the file or directory cannot be found.
        ///The process is aborted..
        /// </summary>
        public static string DialogMessageDirectoryNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder to save is not found! Process is aborted..
        /// </summary>
        public static string DialogMessageDirectoryNotFount {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are files or folders that be encrypted or decrypted, and they are mixed, they does not exists. So, AttacheCase can not determine which should encrypt or decrypt either. It stopped the process..
        /// </summary>
        public static string DialogMessageDragAndDropMixedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDragAndDropMixedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to access an unavailable drive or share.
        ///The process is aborted..
        /// </summary>
        public static string DialogMessageDriveNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDriveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password file is not found in encryption..
        /// </summary>
        public static string DialogMessageEncryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageEncryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It contains the executable files in the decrypted file.
        ///Do you run the following file?.
        /// </summary>
        public static string DialogMessageExecutableFile {
            get {
                return ResourceManager.GetString("DialogMessageExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File association was successful.
        /// </summary>
        public static string DialogMessageFileAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File association tool is not found..
        /// </summary>
        public static string DialogMessageFileAssociationToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File association tool can be not launched..
        /// </summary>
        public static string DialogMessageFileAssociationToolNotLaunched {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal file index is invalid in encrypted file..
        /// </summary>
        public static string DialogMessageFileIndexInvalid {
            get {
                return ResourceManager.GetString("DialogMessageFileIndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file in the following specified file&apos;s list can not be found!.
        /// </summary>
        public static string DialogMessageFileInFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileInFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character encoding of the following specified file is unknown that can not be read!.
        /// </summary>
        public static string DialogMessageFileListEncodingUnknown {
            get {
                return ResourceManager.GetString("DialogMessageFileListEncodingUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following specified list file can not be found!.
        /// </summary>
        public static string DialogMessageFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to access a file that does not exist on the disk failed.
        ///The process is aborted..
        /// </summary>
        public static string DialogMessageFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A managed assembly was found but could not be loaded.
        ///The process is aborted..
        /// </summary>
        public static string DialogMessageFileNotLoaded {
            get {
                return ResourceManager.GetString("DialogMessageFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting files or folders are not found..
        /// </summary>
        public static string DialogMessageFilesNotFoundDelete {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files or folders that move to trash is not found..
        /// </summary>
        public static string DialogMessageFilesNotFoundMoveToTrash {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File disassociation was successful..
        /// </summary>
        public static string DialogMessageFileUnAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileUnAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has been encrypted with a higher version.
        ///It can not be decrypted. The process is aborted..
        /// </summary>
        public static string DialogMessageHigherVersion {
            get {
                return ResourceManager.GetString("DialogMessageHigherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of files or folders are invalid. The process is aborted..
        /// </summary>
        public static string DialogMessageInvalidFilePath {
            get {
                return ResourceManager.GetString("DialogMessageInvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not the private key of the encrypted pair. Could not decrypt..
        /// </summary>
        public static string DialogMessageInvalidPrivateKey {
            get {
                return ResourceManager.GetString("DialogMessageInvalidPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free space on the following disk. The process is aborted..
        /// </summary>
        public static string DialogMessageNoDiskSpace {
            get {
                return ResourceManager.GetString("DialogMessageNoDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not encrypted file. The process is aborted..
        /// </summary>
        public static string DialogMessageNotAtcFile {
            get {
                return ResourceManager.GetString("DialogMessageNotAtcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not use the folder to the password file..
        /// </summary>
        public static string DialogMessageNotDirectoryInPasswordFile {
            get {
                return ResourceManager.GetString("DialogMessageNotDirectoryInPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not the same hash value. Whether the file is corrupted, it may have been made the falsification.The process is aborted..
        /// </summary>
        public static string DialogMessageNotSameHash {
            get {
                return ResourceManager.GetString("DialogMessageNotSameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following characters cannot be used for the file name of Windows.
        ///
        ///\\ / : , * ? \&quot; &lt; &gt; |.
        /// </summary>
        public static string DialogMessageNotUseWindowsFileName {
            get {
                return ResourceManager.GetString("DialogMessageNotUseWindowsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now does not correspond to the decryption of password-protected ZIP file..
        /// </summary>
        public static string DialogMessageNotZipDecrypted {
            get {
                return ResourceManager.GetString("DialogMessageNotZipDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting of Windows XP compatibility mode could not be completed. If Setting is not completed, the application can not be started.
        ///Please start again from the beginning..
        /// </summary>
        public static string DialogMessageNoXpCompatiblityMode {
            get {
                return ResourceManager.GetString("DialogMessageNoXpCompatiblityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There decrypted file is {0} or more.
        ///But, open all of the files associated with application?.
        /// </summary>
        public static string DialogMessageOpenMultipleFiles {
            get {
                return ResourceManager.GetString("DialogMessageOpenMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system denied access due to I/O error or 
        ///certain types of security errors. The process is aborted..
        /// </summary>
        public static string DialogMessageOsDeniesAccess {
            get {
                return ResourceManager.GetString("DialogMessageOsDeniesAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not found that specified in setting panel..
        /// </summary>
        public static string DialogMessagePasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessagePasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Passwords do not match, it is invalid.
        ///Input them again..
        /// </summary>
        public static string DialogMessagePasswordsNotMatch {
            get {
                return ResourceManager.GetString("DialogMessagePasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path name or fully qualified file name exceeds the system-defined maximum length.
        ///The process is aborted..
        /// </summary>
        public static string DialogMessagePathTooLong {
            get {
                return ResourceManager.GetString("DialogMessagePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following specified text file of registration code can not be found!.
        /// </summary>
        public static string DialogMessageRegistrationCodeFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete registration code..
        /// </summary>
        public static string DialogMessageRegistrationCodeNotDeleted {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration code was not successfully registered..
        /// </summary>
        public static string DialogMessageRegistrationCodeNotRegistered {
            get {
                return ResourceManager.GetString("DialogMessageRegistrationCodeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A different pair of keys from the RSA-encrypted public key has been specified. Cannot decrypt.
        ///The process is aborted..
        /// </summary>
        public static string DialogMessageRsaKeyGuidNotMatch {
            get {
                return ResourceManager.GetString("DialogMessageRsaKeyGuidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup tool is not found!.
        /// </summary>
        public static string DialogMessageSetupToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageSetupToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since it is using temporary settings from command line options, it cannot reflect the main settings..
        /// </summary>
        public static string DialogMessageTempSettingsFromCommandLine {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsFromCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since it is using temporary settings from INI files, it cannot reflect the main settings..
        /// </summary>
        public static string DialogMessageTempSettingsFromIniFile {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsFromIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflects the temporarily loaded settings in the registry as the current settings. Are you sure?.
        /// </summary>
        public static string DialogMessageTempSettingsToCurrent {
            get {
                return ResourceManager.GetString("DialogMessageTempSettingsToCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected decrypted files. It stopped the process..
        /// </summary>
        public static string DialogMessageUnexpectedDecryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedDecryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. And stops processing..
        /// </summary>
        public static string DialogMessageUnexpectedError {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string DialogTitleAlert {
            get {
                return ResourceManager.GetString("DialogTitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input encrypted file name for putting together.
        /// </summary>
        public static string DialogTitleAllPackFiles {
            get {
                return ResourceManager.GetString("DialogTitleAllPackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line.
        /// </summary>
        public static string DialogTitleCommandLine {
            get {
                return ResourceManager.GetString("DialogTitleCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to encrypt.
        /// </summary>
        public static string DialogTitleEncryptSelectFiles {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to encrypt.
        /// </summary>
        public static string DialogTitleEncryptSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        public static string DialogTitleInfomation {
            get {
                return ResourceManager.GetString("DialogTitleInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string DialogTitleRegistry {
            get {
                return ResourceManager.GetString("DialogTitleRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a public key and private key.
        /// </summary>
        public static string DialogTitleSavePublicAndPrivateKey {
            get {
                return ResourceManager.GetString("DialogTitleSavePublicAndPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select encrypted files..
        /// </summary>
        public static string DialogTitleSelectEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogTitleSelectEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Password file.
        /// </summary>
        public static string DialogTitleSelectPasswordFile {
            get {
                return ResourceManager.GetString("DialogTitleSelectPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string DialogTitleSettings {
            get {
                return ResourceManager.GetString("DialogTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory to which you save the file or folder to decrypt always..
        /// </summary>
        public static string folderBrowserDialogSaveToDecryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToDecryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to save the encrypted file always..
        /// </summary>
        public static string folderBrowserDialogSaveToEncryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToEncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to save the zip file with password always..
        /// </summary>
        public static string folderBrowserDialogSaveToZipFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be changed while loading the configuration file (INI file).
        /// </summary>
        public static string groupBoxCanNotChange {
            get {
                return ResourceManager.GetString("groupBoxCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting file (INI file) option:.
        /// </summary>
        public static string groupBoxReadIniFile {
            get {
                return ResourceManager.GetString("groupBoxReadIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string labelCaptionAborted {
            get {
                return ResourceManager.GetString("labelCaptionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string labelCaptionAllSkipped {
            get {
                return ResourceManager.GetString("labelCaptionAllSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string labelCaptionCanceled {
            get {
                return ResourceManager.GetString("labelCaptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string labelCaptionCompleted {
            get {
                return ResourceManager.GetString("labelCaptionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred..
        /// </summary>
        public static string labelCaptionError {
            get {
                return ResourceManager.GetString("labelCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match, it is invalid..
        /// </summary>
        public static string labelCaptionPasswordInvalid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password matches, it is valid..
        /// </summary>
        public static string labelCaptionPasswordValid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is incorrect..
        /// </summary>
        public static string labelCodeIncorrect {
            get {
                return ResourceManager.GetString("labelCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial license applicable.
        /// </summary>
        public static string labelCommercialLicenseApplicable {
            get {
                return ResourceManager.GetString("labelCommercialLicenseApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during complete deleting files or folders..
        /// </summary>
        public static string labelCompleteDeleteError {
            get {
                return ResourceManager.GetString("labelCompleteDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete deleting files or folder has been canceled..
        /// </summary>
        public static string labelCompleteDeleteFileCanceled {
            get {
                return ResourceManager.GetString("labelCompleteDeleteFileCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files or folders complete deleting is completed normally..
        /// </summary>
        public static string labelCompleteDeletingCompleted {
            get {
                return ResourceManager.GetString("labelCompleteDeletingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified files or folders has been deleted Completely..
        /// </summary>
        public static string labelCompletelyDeleteCompleted {
            get {
                return ResourceManager.GetString("labelCompletelyDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compression should be performed on the file..
        /// </summary>
        public static string labelCompressMsgNone {
            get {
                return ResourceManager.GetString("labelCompressMsgNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compression operation should be optimally compressed, even if the operation takes a longer time to complete..
        /// </summary>
        public static string labelCompressMsgOptimal {
            get {
                return ResourceManager.GetString("labelCompressMsgOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        public static string labelCompressTitleFastest {
            get {
                return ResourceManager.GetString("labelCompressTitleFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoCompression.
        /// </summary>
        public static string labelCompressTitleNone {
            get {
                return ResourceManager.GetString("labelCompressTitleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal.
        /// </summary>
        public static string labelCompressTitleOptimal {
            get {
                return ResourceManager.GetString("labelCompressTitleOptimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following directory already exists. Do you overwrite the directory to save?.
        /// </summary>
        public static string labelConfirmToOverwriteDir {
            get {
                return ResourceManager.GetString("labelConfirmToOverwriteDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file already exists. Do you overwrite the files to save?.
        /// </summary>
        public static string labelConfirmToOverwriteFile {
            get {
                return ResourceManager.GetString("labelConfirmToOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption was canceled..
        /// </summary>
        public static string labelDecryptionCanceled {
            get {
                return ResourceManager.GetString("labelDecryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption was canceled..
        /// </summary>
        public static string labelDecyptionCanceled {
            get {
                return ResourceManager.GetString("labelDecyptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when deleting files or folders..
        /// </summary>
        public static string labelDeleteError {
            get {
                return ResourceManager.GetString("labelDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string labelDeleteMessageBytes {
            get {
                return ResourceManager.GetString("labelDeleteMessageBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string labelDeleteTypeRandom {
            get {
                return ResourceManager.GetString("labelDeleteTypeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeros.
        /// </summary>
        public static string labelDeleteTypeZeros {
            get {
                return ResourceManager.GetString("labelDeleteTypeZeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of WinZipAes128 and WinZipAes256 are not part of the Zip specification, but rather imply the use of a vendor-specific extension from WinZip. If you want to produce interoperable Zip archives, do not use these values. For example, if you produce a zip archive using WinZipAes256, you will be able to open it in Windows Explorer on Windows XP and Vista, but you will not be able to extract entries; trying this will lead to an &quot;unspecified error&quot;. For this reason, some people have said that a zip archive t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string labelEncryptAlgoDescriptionAES {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkzipWeak implies the use of Zip 2.0 encryption, which is known to be weak and subvertible. 
        ///
        ///A note on interoperability: Values of PkzipWeak and None are specified in PKWARE&apos;s zip specification, and are considered to be &quot;standard&quot;. Zip archives produced using these options will be interoperable with many other zip tools and libraries, including Windows Explorer..
        /// </summary>
        public static string labelEncryptAlgoDescriptionPkzipWeak {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionPkzipWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption process was aborted because the self-executable file could exceed 4GiB..
        /// </summary>
        public static string labelEncryptionAbortedToExceed4GiB {
            get {
                return ResourceManager.GetString("labelEncryptionAbortedToExceed4GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption was canceled..
        /// </summary>
        public static string labelEncryptionCanceled {
            get {
                return ResourceManager.GetString("labelEncryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready for decryption....
        /// </summary>
        public static string labelGettingReadyForDecryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready for encryption....
        /// </summary>
        public static string labelGettingReadyForEncryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password again to confirm:.
        /// </summary>
        public static string labelInputPasswordAgainToConfirm {
            get {
                return ResourceManager.GetString("labelInputPasswordAgainToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character string in path. Do you replace it and decrypt it?.
        /// </summary>
        public static string labelInvalidChar {
            get {
                return ResourceManager.GetString("labelInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public or private key was not loaded..
        /// </summary>
        public static string labelKeyFileNotLoaded {
            get {
                return ResourceManager.GetString("labelKeyFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Completely.
        /// </summary>
        public static string labellabelCompletelyDelete {
            get {
                return ResourceManager.GetString("labellabelCompletelyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Trash.
        /// </summary>
        public static string labelMoveToTrash {
            get {
                return ResourceManager.GetString("labelMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files or folders to the trash has been canceled..
        /// </summary>
        public static string labelMoveToTrashCanceled {
            get {
                return ResourceManager.GetString("labelMoveToTrashCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files or folders to the trash was completed..
        /// </summary>
        public static string labelMoveToTrashCompleted {
            get {
                return ResourceManager.GetString("labelMoveToTrashCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Deleting.
        /// </summary>
        public static string labelNormalDelete {
            get {
                return ResourceManager.GetString("labelNormalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting files or folders has been canceled..
        /// </summary>
        public static string labelNormalDeleteCanceled {
            get {
                return ResourceManager.GetString("labelNormalDeleteCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified files or folders has been deleted..
        /// </summary>
        public static string labelNormalDeleteCompleted {
            get {
                return ResourceManager.GetString("labelNormalDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password file:.
        /// </summary>
        public static string labelPasswordFile {
            get {
                return ResourceManager.GetString("labelPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password file is entered already:.
        /// </summary>
        public static string labelPasswordFileIsEnteredAlready {
            get {
                return ResourceManager.GetString("labelPasswordFileIsEnteredAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard memorized password and input new password:.
        /// </summary>
        public static string labelPasswordInputNewPassword {
            get {
                return ResourceManager.GetString("labelPasswordInputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The memorized password:.
        /// </summary>
        public static string labelPasswordMemorized {
            get {
                return ResourceManager.GetString("labelPasswordMemorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of command line option:.
        /// </summary>
        public static string labelPasswordOfCommandLineOption {
            get {
                return ResourceManager.GetString("labelPasswordOfCommandLineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete completely is completed successfully..
        /// </summary>
        public static string labelProcessDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready for encryption....
        /// </summary>
        public static string labelProcessGettingRedyForEncryption {
            get {
                return ResourceManager.GetString("labelProcessGettingRedyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting....
        /// </summary>
        public static string labelProcessNameDecrypt {
            get {
                return ResourceManager.GetString("labelProcessNameDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string labelProcessNameDelete {
            get {
                return ResourceManager.GetString("labelProcessNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Completely....
        /// </summary>
        public static string labelProcessNameDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessNameDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting....
        /// </summary>
        public static string labelProcessNameEncrypt {
            get {
                return ResourceManager.GetString("labelProcessNameEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Trash....
        /// </summary>
        public static string labelProcessNameMoveToTrash {
            get {
                return ResourceManager.GetString("labelProcessNameMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key
        ///Encrypt.
        /// </summary>
        public static string labelRsa {
            get {
                return ResourceManager.GetString("labelRsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop the file or folder you want to encrypt or decrypt here. You can also drag and drop the public key and private key first..
        /// </summary>
        public static string labelRsaDescription {
            get {
                return ResourceManager.GetString("labelRsaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted file has been loaded. Drag and drop the private key to be decrypted here..
        /// </summary>
        public static string labelRsaEncryptedFileloaded {
            get {
                return ResourceManager.GetString("labelRsaEncryptedFileloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or folder has been loaded. Drag and drop public key to be encrypted here..
        /// </summary>
        public static string labelRsaFilesloaded {
            get {
                return ResourceManager.GetString("labelRsaFilesloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop the file or folder you want to encrypt or decrypt here. You can also drag and drop the public key and private key first..
        /// </summary>
        public static string labelRsaMessage {
            get {
                return ResourceManager.GetString("labelRsaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string labelRsaPrivateKey {
            get {
                return ResourceManager.GetString("labelRsaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key has been loaded. Drag and drop the encrypted file to be decrypted here..
        /// </summary>
        public static string labelRsaPrivateKeyloaded {
            get {
                return ResourceManager.GetString("labelRsaPrivateKeyloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string labelRsaPublicKey {
            get {
                return ResourceManager.GetString("labelRsaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public key has been loaded. Drag and drop the ​file or folder to be encrypted here..
        /// </summary>
        public static string labelRsaPublicKeyloaded {
            get {
                return ResourceManager.GetString("labelRsaPublicKeyloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid code..
        /// </summary>
        public static string labelValidCode {
            get {
                return ResourceManager.GetString("labelValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compression operation should complete as quickly as possible, even if the resulting file is not optimally compressed..
        /// </summary>
        public static string lbelCompressMsgFastest {
            get {
                return ResourceManager.GetString("lbelCompressMsgFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting updates information is failed..
        /// </summary>
        public static string linkLabelCheckForUpdatesFailed {
            get {
                return ResourceManager.GetString("linkLabelCheckForUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for update....
        /// </summary>
        public static string linkLabelCheckingForUpdates {
            get {
                return ResourceManager.GetString("linkLabelCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is latest..
        /// </summary>
        public static string linkLabelLatestVersion {
            get {
                return ResourceManager.GetString("linkLabelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version is released!.
        /// </summary>
        public static string linkLabelLatestVersionReleased {
            get {
                return ResourceManager.GetString("linkLabelLatestVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        public static string MessageBoxButtonAbort {
            get {
                return ResourceManager.GetString("MessageBoxButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string MessageBoxButtonCancel {
            get {
                return ResourceManager.GetString("MessageBoxButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Proceed.
        /// </summary>
        public static string MessageBoxButtonProceed {
            get {
                return ResourceManager.GetString("MessageBoxButtonProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info:
        ///To ensure that the file is decrypted correctly, the unique value (MD5 hash) of the original file is written to the file before encryption and is checked during decryption.
        ///
        ///- Encrypted file hash value: {0}
        ///- File hash value after decryption: {1}.
        ///
        ///If these hash values do not match, the file may have been modified from its original state or corrupted. Please use this information to determine if you wish to proceed with decryption..
        /// </summary>
        public static string MessageBoxDetailedInformation {
            get {
                return ResourceManager.GetString("MessageBoxDetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify the following file. The files may have been modified or corrupted. How do I proceed?.
        /// </summary>
        public static string MessageBoxFileVerifyFailed {
            get {
                return ResourceManager.GetString("MessageBoxFileVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;Details.
        /// </summary>
        public static string MessageBoxHideDetails {
            get {
                return ResourceManager.GetString("MessageBoxHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show&amp;Details.
        /// </summary>
        public static string MessageBoxShowDetails {
            get {
                return ResourceManager.GetString("MessageBoxShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files(*.*)|*.*.
        /// </summary>
        public static string OpenDialogFilterAllFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon files(*.ico)|*.ico|All files(*.*)|*.*.
        /// </summary>
        public static string OpenDialogFilterIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Icon files.
        /// </summary>
        public static string OpenDialogTitleIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogTitleIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATC files (*.atc)|*.atc|All files (*.*)|*.*.
        /// </summary>
        public static string SaveDialogFilterAtcFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterAtcFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INI files (*.ini)|*.ini|All files (*.*)|*.*.
        /// </summary>
        public static string SaveDialogFilterIniFilles {
            get {
                return ResourceManager.GetString("SaveDialogFilterIniFilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Executable file(*.exe)|*.exe|All files(*.*)|*.*.
        /// </summary>
        public static string SaveDialogFilterSelfExeFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterSelfExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerable.
        /// </summary>
        public static string zxcvbnLabel00 {
            get {
                return ResourceManager.GetString("zxcvbnLabel00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string zxcvbnLabel01 {
            get {
                return ResourceManager.GetString("zxcvbnLabel01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhat weak.
        /// </summary>
        public static string zxcvbnLabel02 {
            get {
                return ResourceManager.GetString("zxcvbnLabel02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string zxcvbnLabel03 {
            get {
                return ResourceManager.GetString("zxcvbnLabel03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string zxcvbnLabel04 {
            get {
                return ResourceManager.GetString("zxcvbnLabel04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string.
        /// </summary>
        public static string zxcvbnLabelEmpty {
            get {
                return ResourceManager.GetString("zxcvbnLabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another word or two. Uncommon words are better..
        /// </summary>
        public static string zxcvbnSuggestionAddAnotherWordOrTwo {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAddAnotherWordOrTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-uppercase is almost as easy to guess as all-lowercase..
        /// </summary>
        public static string zxcvbnSuggestionAllCapsEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAllCapsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid dates and years that are associated with you..
        /// </summary>
        public static string zxcvbnSuggestionAvoidDatesYearsAssociatedYou {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidDatesYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid repeated words and characters..
        /// </summary>
        public static string zxcvbnSuggestionAvoidRepeatedWordsAndChars {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidRepeatedWordsAndChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid sequences..
        /// </summary>
        public static string zxcvbnSuggestionAvoidSequences {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid recent years. Avoid years that are associated with you..
        /// </summary>
        public static string zxcvbnSuggestionAvoidYearsAssociatedYou {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization doesn&apos;t help very much..
        /// </summary>
        public static string zxcvbnSuggestionCapsDontHelp {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionCapsDontHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a few words, avoid common phrases. No need for symbols, digits, or uppercase letters..
        /// </summary>
        public static string zxcvbnSuggestionDefault {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string..
        /// </summary>
        public static string zxcvbnSuggestionEmpty {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictable substitutions like &apos;@&apos; instead of &apos;a&apos; don&apos;t help very much..
        /// </summary>
        public static string zxcvbnSuggestionPredictableSubstitutionsEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionPredictableSubstitutionsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed words aren&apos;t much harder to guess..
        /// </summary>
        public static string zxcvbnSuggestionReversedWordEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionReversedWordEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a longer keyboard pattern with more turns..
        /// </summary>
        public static string zxcvbnSuggestionUseLongerKeyboardPattern {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionUseLongerKeyboardPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string zxcvbnToolTipTitleSuggestions {
            get {
                return ResourceManager.GetString("zxcvbnToolTipTitleSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string zxcvbnToolTipTitleWarning {
            get {
                return ResourceManager.GetString("zxcvbnToolTipTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates are often easy to guess..
        /// </summary>
        public static string zxcvbnWarnigDatesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarnigDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common names and surnames are easy to guess..
        /// </summary>
        public static string zxcvbnWarningCommonNameSurnamesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningCommonNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a very common password..
        /// </summary>
        public static string zxcvbnWarningCommonPasswords {
            get {
                return ResourceManager.GetString("zxcvbnWarningCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates are often easy to guess..
        /// </summary>
        public static string zxcvbnWarningDatesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string..
        /// </summary>
        public static string zxcvbnWarningDefault {
            get {
                return ResourceManager.GetString("zxcvbnWarningDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty String..
        /// </summary>
        public static string zxcvbnWarningEmpty {
            get {
                return ResourceManager.GetString("zxcvbnWarningEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names and surnames by themselves are easy to guess..
        /// </summary>
        public static string zxcvbnWarningNameSurnamesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent years are easy to guess..
        /// </summary>
        public static string zxcvbnWarningRecentYearsEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningRecentYearsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats like &apos;aaa&apos; are easy to guess..
        /// </summary>
        public static string zxcvbnWarningRepeatsLikeAaaEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningRepeatsLikeAaaEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats like &apos;abcabcabc&apos; are only slightly harder to guess than &apos;abc&apos;..
        /// </summary>
        public static string zxcvbnWarningRepeatsLikeAbcSlighterHarder {
            get {
                return ResourceManager.GetString("zxcvbnWarningRepeatsLikeAbcSlighterHarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences like abc or 6543 are easy to guess..
        /// </summary>
        public static string zxcvbnWarningSequenceAbcEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningSequenceAbcEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short keyboard patterns are easy to guess..
        /// </summary>
        public static string zxcvbnWarningShortKeyboardPatterns {
            get {
                return ResourceManager.GetString("zxcvbnWarningShortKeyboardPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is similar to a commonly used password..
        /// </summary>
        public static string zxcvbnWarningSimilarCommonPasswords {
            get {
                return ResourceManager.GetString("zxcvbnWarningSimilarCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight rows of keys are easy to guess..
        /// </summary>
        public static string zxcvbnWarningStraightRow {
            get {
                return ResourceManager.GetString("zxcvbnWarningStraightRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a top-10 common password..
        /// </summary>
        public static string zxcvbnWarningTop10Passwords {
            get {
                return ResourceManager.GetString("zxcvbnWarningTop10Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A word by itself is easy to guess..
        /// </summary>
        public static string zxcvbnWarningWordEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningWordEasy", resourceCulture);
            }
        }
    }
}
